name: Generar APK MiPareja

on:
  workflow_dispatch:

jobs:
  build:
    name: Crear APK Android
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependencias
        run: npm install

      - name: Instalar EAS CLI
        run: npm install --global eas-cli

      - name: Crear APK
        run: eas build --platform android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
